# Generated by Django 5.1.1 on 2024-09-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0002_product_users_like_comment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='group',
        ),
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='olcha.category'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to='group/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
